/**
 * Mock reward items for iReward Store.
 * Categories: time_off | merch | privilege | digital | experience
 * Coin prices range 80–2000. User (coinBalance=240) can afford items ≤240.
 */

import type { RewardItem } from '@/types/reward.types';

const NOW = new Date().toISOString();

export const MOCK_REWARDS: RewardItem[] = [
  {
    item_id: 'rwd-001',
    name: 'Ngày nghỉ thưởng',
    description: 'Thêm 1 ngày nghỉ phép có lương. P&OD xác nhận trong 2 ngày làm việc.',
    category: 'time_off',
    coin_price: 500,
    stock: 10,
    max_per_user: 2,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd1/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-002',
    name: 'WFH Bonus 1 ngày',
    description: 'Làm việc từ xa thêm 1 ngày ngoài chính sách thông thường.',
    category: 'privilege',
    coin_price: 300,
    stock: 20,
    max_per_user: 4,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd2/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-003',
    name: 'Voucher Grab Food 100K',
    description: 'Voucher đặt đồ ăn Grab Food trị giá 100,000đ.',
    category: 'digital',
    coin_price: 150,
    stock: 50,
    max_per_user: null,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd3/400/300',
    fulfillment_type: 'auto',
  },
  {
    item_id: 'rwd-004',
    name: 'Voucher The Coffee House',
    description: 'Voucher nước uống The Coffee House trị giá 50,000đ.',
    category: 'digital',
    coin_price: 100,
    stock: 30,
    max_per_user: null,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd4/400/300',
    fulfillment_type: 'auto',
  },
  {
    item_id: 'rwd-005',
    name: 'Áo iKame Limited Edition',
    description: 'Áo thun iKame phiên bản giới hạn 2026. Chất liệu cotton cao cấp.',
    category: 'merch',
    coin_price: 400,
    stock: 15,
    max_per_user: 1,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd5/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-006',
    name: 'Mũ iKame Branded',
    description: 'Mũ lưỡi trai iKame thêu logo. Phong cách, bền đẹp.',
    category: 'merch',
    coin_price: 200,
    stock: 25,
    max_per_user: 2,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd6/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-007',
    name: 'Laptop Sticker Pack',
    description: 'Bộ sticker iKame + tech quotes chất lượng cao, không bong tróc.',
    category: 'merch',
    coin_price: 80,
    stock: null,
    max_per_user: null,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd7/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-008',
    name: 'Flexible Check-in 1 tuần',
    description: 'Được check-in linh hoạt (muộn tối đa 2 tiếng) trong 1 tuần làm việc.',
    category: 'privilege',
    coin_price: 800,
    stock: 5,
    max_per_user: 1,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd8/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-009',
    name: 'Khóa học Udemy',
    description: 'Một khóa học bất kỳ trên Udemy. Giá trị tối đa $19.99.',
    category: 'experience',
    coin_price: 600,
    stock: null,
    max_per_user: 2,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd9/400/300',
    fulfillment_type: 'manual',
  },
  {
    item_id: 'rwd-010',
    name: 'Team Lunch với CEO',
    description: 'Cơ hội ngồi ăn trưa và trò chuyện trực tiếp với CEO iKame.',
    category: 'experience',
    coin_price: 2000,
    stock: 3,
    max_per_user: 1,
    available_from: NOW, available_to: null,
    is_active: true, image_url: 'https://picsum.photos/seed/rwd10/400/300',
    fulfillment_type: 'manual',
  },
];
